### ISSUE TITLE
Pinecone upsert raw error

### ISSUE THREAD

**Issue by xingfanxia** [mayooear/notion-chat-langchain#1]
Hi, I'm getting an error with ingestion. And it's not clear what the issue is...
```
creating vector store...
error PineconeClient: Error calling upsert: PineconeClient: Error calling upsertRaw: ResponseError: Response returned an error code  
/Users/xingfanxia/projects/notion-chat-langchain/scripts/ingest-data.ts:38
    throw new Error('Failed to ingest your data');
          ^


Error: Failed to ingest your data
    at run (/Users/xingfanxia/projects/notion-chat-langchain/scripts/ingest-data.ts:38:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/xingfanxia/projects/notion-chat-langchain/scripts/ingest-data.ts:43:3)

Node.js v18.15.0
```

**Comment by xingfanxia** [comment]
Is there any specific requirement for the index? This is my index
![Monosnap Pinecone Console 2023-03-21 02-16-53](https://user-images.githubusercontent.com/8936233/226562853-b134199b-636b-4046-8ea4-b14a9ab5bea1.jpg)

**Comment by xingfanxia** [comment]
this method's signature looks different from Langchain source code 
```  
static async fromDocuments(
    docs: Document[],
    embeddings: Embeddings,
    dbConfig: PineconeLibArgs
  ): Promise<PineconeStore> {
    const args = dbConfig;
    args.textKey = dbConfig.textKey ?? "text";

    const instance = new this(embeddings, args);
    await instance.addDocuments(docs);
    return instance;
  }
```

**Comment by xingfanxia** [comment]
The langchain api is poorly written, there's no other error details except for this message...

**Comment by xingfanxia** [comment]
I tried out this one https://github.com/hwchase17/notion-qa. It does ingest ok, but the faiss index is not as good tho

**Comment by xingfanxia** [comment]
It does not support other language other than English as well

**Comment by xingfanxia** [comment]
seems to be related to this issue..https://github.com/pinecone-io/pinecone-ts-client/issues/16

**Comment by xingfanxia** [comment]
It's a problem with outdated dependency which doesn't throw proper error when the docs length is too long/too big

**Comment by mchaney22** [comment]
What did you need to update?
